Name = "Opal.UnitTests"
Language = "C++"
Version = "1.0.0"
Type = "Executable"
Source = [
	"gen/Main.cpp"
]
IncludePaths = [
	"./",
]

[Dependencies]
Runtime = [
	"Soup.Test.Assert@0.1.8",
	"../Source/",
]